### ISSUE TITLE
Implement rfcsubseries data fetching

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/relaton-data-rfcsubseries#1]
Data source: https://www.rfc-editor.org/rfc-index.xml

The current implemtnation is at this link:
https://trac.ietf.org/trac/xml2rfc/browser/website/rfcs/bibxml/bibxml-rfcsubseries

We have to parse the following entries:
* `<bcp-entry>`
* `<fyi-entry>`
* `<std-entry>`

**Comment by andrew2net** [comment]
@ronaldtse current implementation outputs:
```xml
<referencegroup anchor="BCP14" target="https://www.rfc-editor.org/info/bcp14">
  <xi:include href="https://www.rfc-editor.org/refs/bibxml/reference.RFC.2119.xml" />
  <xi:include href="https://www.rfc-editor.org/refs/bibxml/reference.RFC.8174.xml" />
</referencegroup>
```
It isn't what the relaton-ietf parses and renders. Shoudl we adopt our relaton model to handle this kind of documents? Or do we just ned to convert `<*-entry>` elements to `<referencegroup>`?

**Comment by ronaldtse** [comment]
Yes, we need to handle these documents as part of the import process only. We do not need to generate this kind of format.

This XML snippet means that "BCP14" is a collection that includes RFC 2119 and RFC 8174.

**Comment by ronaldtse** [comment]
And in the corresponding RFC entry from index.xml, we need to have the "link" to the BCP it belongs to:

```xml
<rfc-entry>
<doc-id>RFC2119</doc-id>
<title>
Key words for use in RFCs to Indicate Requirement Levels
</title>
<author>
<name>S. Bradner</name>
</author>
<date>
<month>March</month>
<year>1997</year>
</date>
<format>
<file-format>ASCII</file-format>
<file-format>HTML</file-format>
</format>
<page-count>3</page-count>
<keywords>
<kw>Standards</kw>
<kw>Track</kw>
<kw>Documents</kw>
</keywords>
<abstract>
<p>
In many standards track documents several words are used to signify the requirements in the specification. These words are often capitalized. This document defines these words as they should be interpreted in IETF documents. This document specifies an Internet Best Current Practices for the Internet Community, and requests discussion and suggestions for improvements.
</p>
</abstract>
<draft>draft-bradner-key-words-03</draft>
<updated-by>
<doc-id>RFC8174</doc-id>
</updated-by>
<is-also>
<doc-id>BCP0014</doc-id>
</is-also>
<current-status>BEST CURRENT PRACTICE</current-status>
<publication-status>BEST CURRENT PRACTICE</publication-status>
<stream>IETF</stream>
<wg_acronym>NON WORKING GROUP</wg_acronym>
<errata-url>
http://www.rfc-editor.org/errata_search.php?rfc=2119
</errata-url>
<doi>10.17487/RFC2119</doi>
</rfc-entry>
```

**Comment by ronaldtse** [comment]
Remember that IETF is not homogeneous, there are 2 parties that produce bibliographic data:
1. RFC Production Center (RPC): they publish RFCs, BCPs etc. (the RFC subseries)
2. Datatracker: publishes Internet-Drafts.

**Comment by andrew2net** [comment]
@ronaldtse in the current implementation's description declared output:
```xml
<referencegroup anchor="BCP14" target="https://www.rfc-editor.org/info/bcp14">
  <xi:include href="https://www.rfc-editor.org/refs/bibxml/reference.RFC.2119.xml" />
  <xi:include href="https://www.rfc-editor.org/refs/bibxml/reference.RFC.8174.xml" />
</referencegroup>
```
but the script reads `reference.RFC.*.xml` file from the local directory and puts its content instead `<xi:include>` element. Should we fetch `https://www.rfc-editor.org/refs/bibxml/reference.RFC.*.xml` documents and replace `<xi:include>` with them?

**Comment by ronaldtse** [comment]
We don't need to resolve xi:includes into XML, we just need to treat them as references (document relations).

**Comment by ronaldtse** [comment]
@andrew2net is this ready to go? Thanks.

**Comment by andrew2net** [comment]
It's implemented but I'm going to publish this gem when finishing https://github.com/ietf-ribose/relaton-data-rfcs/issues/1 this weelend

**Comment by ronaldtse** [comment]
Got it, thanks!

**Comment by andrew2net** [comment]
@ronaldtse I've pushed the parsed data. Can you confirm if the files have correct format?

**Comment by ronaldtse** [comment]
Thanks @andrew2net . 

@kwkwan @strogonoff Right now the bibxml-service is configured to use the bibxml-data-rfcsubseries repository. Can you change the demo instance to load from the new repositories? Thanks.
