### ISSUE TITLE
Data format not in Relaton

### ISSUE THREAD

**Issue by ronaldtse** [ietf-ribose/relaton-data-rfcsubseries#2]
@andrew2net the data format used in this repository does not look like Relaton. It needs to be in the Relaton-IETF format.

e.g. 
```xml
<referencegroup xmlns:xi="http://www.w3.org/2001/XInclude" anchor="BCP76" target="https://www.rfc-editor.org/info/bcp76">
  <xi:include href="https://www.rfc-editor.org/refs/bibxml/reference.RFC.3666.xml"/>
</referencegroup>
```

**Comment by andrew2net** [comment]
@ronaldtse relaton doesn't support `<referencegroup>` element in BibXML output. I asked about it here https://github.com/ietf-ribose/relaton-data-rfcsubseries/issues/1#issuecomment-993793894. It seems I misunderstood you.
If we need to handle this kind of element in Relaton model then we need to define a special type of relation and update parsing and rendering BibXML.

**Comment by ronaldtse** [comment]
@andrew2net Relaton does support this notion.

![](https://github.com/relaton/relaton-models/raw/main/images/RelBib_DocumentRelation.png)

A BCP is a document type that can "include" multiple documents.

There are two Relaton relationships that can apply: "includes", "hasPart".

("hasInstance" doesn't work because "Instance" is in the FBIR sense which means "an instantiation of a work".)

I'm thinking to use the "includes" relation. i.e. BCP X includes RFC Y and RFC Z. However, I'm not sure if it conveys the meaning of "consists of". i.e. BCP X consists of exactly 2 parts. 

I guess "includes" is good enough.

**Comment by andrew2net** [comment]
Ok, let's make `includes` special for this case.
@opoudjis do you have an objection if we use the relation type `includes` as a special type?

**Comment by ronaldtse** [comment]
@andrew2net why is `includes` a special type? We're just using something that exists in Relaton. Don't understand...

**Comment by andrew2net** [comment]
@ronaldtse normal Relaton document is rendered in BibXML format as:
```xml
<reference anchor="RFC3666" target="https://www.rfc-editor.org/info/rfc3666">
  <front>
    <title>Session Initiation Protocol (SIP) Public Switched Telephone Network (PSTN) Call Flows</title>
    <author initials="A." surname="Johnston" fullname="A. Johnston">
      <organization/>
    </author>
    <date year="2003" month="December"/>
    <abstract><t>This document contains ...</t></abstract>
  </front>
  <seriesInfo name="BCP" value="76"/>
</reference>
```
so if we want to render documents like this:
```xml
<referencegroup xmlns:xi="http://www.w3.org/2001/XInclude" anchor="BCP76" target="https://www.rfc-editor.org/info/bcp76">
  <xi:include href="https://www.rfc-editor.org/refs/bibxml/reference.RFC.3666.xml"/>
</referencegroup>
```
we need to recognize if the document is a collection of other documents. I suggest if a document has `includes` type of relations then we render it as `<referencegroup>` collection.

**Comment by opoudjis** [comment]
includes is indeed the correct relation type.

**Comment by ronaldtse** [comment]
@andrew2net in BibXML, yes we need to render a BCP/STD as a `<referencegroup>` according to [RFC 7991](https://datatracker.ietf.org/doc/html/rfc7991#section-2.41).

```
1.3.1
   ...
   o  Add <referencegroup> to allow referencing multi-RFC documents such
      as STDs and BCPs.
```

```
2.41.  <referencegroup>

   Represents a list of bibliographic references that will be
   represented as a single reference.  This is most often used to
   reference STDs and BCPs, where a single reference (such as "BCP 9")
   may encompass more than one RFC.

   This element appears as a child element of <references>
   (Section 2.42).

   Content model:

   One or more <reference> elements (Section 2.40)
```

Notice that we have two options of rendering:

1. Using `xi:include`
```xml
<referencegroup xmlns:xi="http://www.w3.org/2001/XInclude" anchor="BCP76" target="https://www.rfc-editor.org/info/bcp76">
  <xi:include href="https://www.rfc-editor.org/refs/bibxml/reference.RFC.3666.xml"/>
</referencegroup>
```

2. Fully expanded
```xml
<referencegroup xmlns:xi="http://www.w3.org/2001/XInclude" anchor="BCP76" target="https://www.rfc-editor.org/info/bcp76">
<reference anchor="RFC3666" target="https://www.rfc-editor.org/info/rfc3666">
  <front>
    <title>Session Initiation Protocol (SIP) Public Switched Telephone Network (PSTN) Call Flows</title>
    <author initials="A." surname="Johnston" fullname="A. Johnston">
      <organization/>
    </author>
    <date year="2003" month="December"/>
    <abstract><t>This document contains ...</t></abstract>
  </front>
  <seriesInfo name="BCP" value="76"/>
</reference>
</referencegroup>
```

And in fact, we should use Option 2 because the BibXML service will be handling the BibXML representation of the RFC:
* i.e. we should not rely on `<xi:include href="https://www.rfc-editor.org/refs/bibxml/reference.RFC.3666.xml"/>`.

What @opoudjis is pointing out is that:
1. We should use "Relaton include" to indicate that a BCP includes those RFCs.
2. In converting a Relaton model into BibXML, if the document type is a BCP, we render it as a `<referencegroup>`.

This should be clear, right?

**Comment by andrew2net** [comment]
> In fact, we have to use Option 2 because the BibXML service will be handling the BibXML representation of the RFC:

@ronaldtse does it mean we need to resolve includes? https://github.com/ietf-ribose/relaton-data-rfcsubseries/issues/1#issuecomment-994676977

**Comment by ronaldtse** [comment]
@andrew2net no, Relaton only needs to do this:

```xml
<referencegroup anchor="BCP76" target="https://www.rfc-editor.org/info/bcp76">
<reference anchor="RFC3666" target="https://www.rfc-editor.org/info/rfc3666">
  <front>
    <title>Session Initiation Protocol (SIP) Public Switched Telephone Network (PSTN) Call Flows</title>
    <author initials="A." surname="Johnston" fullname="A. Johnston">
      <organization/>
    </author>
    <date year="2003" month="December"/>
    <abstract><t>This document contains ...</t></abstract>
  </front>
  <seriesInfo name="BCP" value="76"/>
</reference>
</referencegroup>
```

All of this information is available from: https://github.com/ietf-ribose/relaton-data-rfcsubseries/issues/1#issue-1071945425

**Comment by ronaldtse** [comment]
Thanks @andrew2net ! Confirmed that the BibXML output is correct.
